pipeline:
  identifier: Build_Harness11_1699428586536
  name: Build Harness11
  orgIdentifier: default
  projectIdentifier: harnesstest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Harness11
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
